Feature Request #1 expand QuestDetails card
Nikurasuu/rdr2quest pull request #4
Opened 2023-02-20 10:56 UTC by Nikurasuu

2023-02-20 12:24 UTC, 42tg requested changes

2023-02-20 12:24 UTC, 42tg commented on src/components/QuestDetails.js
> +const containerHeight = window.innerHeight-185;
I personally don't like those `window.innerXY` calculations.

It would be great if you can solve it by another way. 

Hint: 
at first try always 
```css 
height: 100%
```

I would pretend that you can solve the whole height issues with it. And completly remove the calculated height attribute.

Just to help you out a bit for the dataTable part https://mui.com/x/react-data-grid/layout/#auto-height should do it somehow.

2023-02-20 13:08 UTC, Nikurasuu commented on src/components/QuestDetails.js
> +const containerHeight = window.innerHeight-185;
`height: 100%` Doesn't work for me, it will still make the Card only as big as needed.

Adding auto-height, makes the Data-Table adjust the height automatically according to the rows, is this correct?

2023-02-20 17:56 UTC, 42tg requested changes
Looks better now.
But not directly what I meant. 

Based on this definition here [Difference Between PX, em ....](https://elementor.com/help/whats-the-difference-between-px-em-rem-vw-and-vh/#:~:text=VH%20is%20useful%20for%20creating,to%20viewport's%20width%20or%20height)

> VH is useful for creating full height elements (100%) that fill up the entire viewport’s height. Of course, you can use any percentage of the viewport’s height to achieve other goals, such as 50% for half the height, etc.
> % is similar to VW and VH but it is not a length that is relative to viewport’s width or height. Instead, it is a percentage of the **_parent element’s width or height_**. Percentage units are often useful to set the width of margins, as an example.

I highlighted the important part of the quote a bit.
To catch you a bit up I don't think that your Components are necessary wrong setup its more the frame around them wich limits the size of the components underneath.

2023-02-20 17:56 UTC, 42tg commented on src/components/QuestDetails.js
> +        <div style={{ height: '80vh', width: '100%' }}>
That's definitive better since we don't want those properties calculated via Javascript but sadly not what I meant.

2023-02-22 10:38 UTC, 42tg approved these changes

2023-02-22 10:39 UTC, merged